#!/usr/bin/env bash

# Install and configure Nginx to serve "Hello World!" page

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
