#!/usr/bin/env bash
# Configure Nginx on web-01 and web-02 to include a custom HTTP header.
# The custom header should be named "X-Served-By" and show the server's hostname.
# Set up a firewall rule to permit requests on port 80.

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

echo 'Hello World!' |sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/channel/UCLvBiHEefvum_V1055VkHVA permanent;"

sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
