#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server.
# Configure HAProxy to send traffic to web-01 and web-02 servers.
# Distribute requests using a round-robin algorithm.
# Ensure that HAProxy can be managed via an init script.

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  MercyNJ-frontend
        bind *:80
        mode http
        default_backend MercyNJ-backend
backend MercyNJ-backend
        balance roundrobin
        server 240357-web-01 100.25.197.219 :80 check
        server 240357-web-02 :80 18.214.89.4 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
