#!/usr/bin/env bash
# Debugging Nginx so that the 'service' command (init ) indicates not running
sudo apt -y install nginx
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
