#!/usr/bin/env bash
#This script creates a file /var/run/myscript.pid containing its PID,
#displays To infinity and beyond indefinitely & I hate the kill command when receiving a SIGTERM signal.
#It also displays Y U no love me?! when receiving a SIGINT signal,deletes the file /var/run/myscript.pid &
# terminates itself when receiving a SIGQUIT or SIGTERM signal.

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT
while true
do 
    echo 'To infinity and beyond' 
    sleep 2
done


