#!/usr/bin/env bash
#This script manages manage_my_process script.
#It starts manage_my_process when provided with arg start,creates a file containing its PID in /var/run/my_process.pid & displays manage_my_process started.
#It stops manage_my_process when provided with arg stop,deletes the file containing its PID /var/run/my_process.pid & displays manage_my_process stoped.
#It restarts manage_my_process when provided with arg restart.
#It displays manage_my_process {start|stop|restart} if any other argument or no argument is passed.

if [ $# -gt 0 ]
then
    if [ "$1" == "start" ]
    then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
    elif [ "$1" == "stop" ]
    then
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
    elif [ "$1" == "restart" ]
    then
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
    else
	echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
