#!/usr/bin/env bash
#This script displays To infinity and beyond indefinitely,with a sleep of 2 In between each iteration of the loop

while true
do
    echo "To infinity and beyond"
    sleep 2
done
