#!/usr/bin/env bash
#This script displays numbers from 1 to 100,FizzBuzz if multiple of 3 and 5,Fizz if multiple of 3 & Buzz multiple of 5

for i in {1..100}; do
       if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
       echo "FizzBuzz"
elif (( i % 3 == 0 )); then
 echo "Fizz"
elif (( i % 5 == 0 )); then
       echo "Buzz"
else
 echo "$i"
fi
done
