#!/usr/bin/env bash
#This script displays content of /etc/passwd file, with specific info captured

while IFS=":" read -r usrname _ usrid _ homedir _; do
echo "$usrname:$usrid:$homedir"
done < "/etc/passwd"
