#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=":" read -r usrname _ userid _ _ homedir shell; do
IFS=":" read -r _ _ _ comment _ <<< "$(grep "^$usrname:" /etc/passwd)"
echo "The user $usrname is part of the $userid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $comment"
done < "/etc/passwd"
