#!/usr/bin/env bash
#This script displays Best School 10 times, using while loop at 9th iteration,displays Hi

i=1
while [[ $i -le 10 ]]; do
if [[ $i == 9 ]]
then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi
(( i += 1 ))
done
