#!/usr/bin/env bash
#This script loops from 1-10,using while loop & if, elif and else statements

i=1
while [[ $i -le 10 ]]; do
if [[ $i == 4 ]];
then
echo "bad luck"
elif [[ $i == 8 ]]; then
echo "good luck"
else
echo "Best School"
fi
(( i += 1 ))
done
