#!/usr/bin/env bash
#This script displays current directory's content,in list format while excluding content before 1st dash

for item in *; do
	if [[ -f $item && ! $item == .* ]]; then
		name=$(echo "$item" | cut -d'-' -f2)
		echo "$name"
	fi
done
