#!/usr/bin/env bash
# A script that configures Nginx to run as nginx user instead of root.

sudo sed -i 's/#user nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
